### ISSUE TITLE
API List / Script Setup

### ISSUE THREAD

**Issue by kayla06** [Sundays211/VirtueRS3#15]
https://github.com/Sundays211/VirtueRS3/wiki/API-List

**Comment by Sundays211** [comment]
The top section (the part about adding "var api" and "api = scriptManager.getApi()") is now redundant since the script changes.

Also note "addSpot" has changed to "setSpotAnim" and "clearAnimation" has changed to "stopAnimation". All methods are defined in org.virtue.engine.script.api.ScriptAPI

**Comment by Sundays211** [comment]
Also, see if you can post this up on the wiki

**Comment by kayla06** [comment]
https://github.com/Sundays211/VirtueRS3/wiki/API-List Posted on wiki. This page will be closed.
